// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import path from 'node:path';
import "dotenv/config";
import { defineConfig,env } from "prisma/config";

export default defineConfig({
  schema: path.join('prisma','schema.prisma'),
  migrations: {
    path: path.join('prisma','migrations')
  },
  datasource: {
    url: env('DATABASE_URL'),
  },
});
